name: "bumpgen"
description: "handle breaking changes from dependency upgrades"
author: Xeol <xeol.io>

inputs:
  path:
    description: Repository path
    required: false
    default: "./"
  llm_key:
    description: "LLM API key"
    required: true
  github_token:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        LLM_API_KEY: ${{ inputs.llm_key }}
      run: |
        npm install -g bumpgen
        bumpgen --simple --dir ${{ inputs.path }} --no-upgrade --auto-detect
    - shell: bash
      name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    - shell: bash
      name: Check for changes and commit
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        git add -A
        if ! git diff-index --quiet HEAD; then
          git commit -m "chore: run bumpgen"
          git push origin HEAD:${GITHUB_REF#refs/heads/}
        else
          echo "No changes to commit"
        fi
