name: Verify Readme Duplicated

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths:
      - README.md
      - apps/cli/README.md

jobs:
  check-readmes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify that the readmes are the same
        run: |
          FILE1='README.md'
          FILE2='apps/cli/README.md'
          HASH1=$(sha256sum $FILE1 | awk '{print $1}')
          HASH2=$(sha256sum $FILE2 | awk '{print $1}')
          if [ "$HASH1" == "$HASH2" ]; then
            echo "Readmes are the same."
          else
            echo "Repo README and CLI README are different."
            exit 1
          fi
